<div class="row" id="divComment<?php echo $c->getId(); ?>">
	<div class="col-1">
	<?php echo '<img src="Views/img/fotosPerfil/'.$c->getUserId().'/'.$c->getUsuario()->getNomeFoto().'" width="50px" height="50px">'; ?>
	</div>

	<div class="col-10 text-light">
		<div class="sonic" >
			<h6 id="nomeuser">
				<?php echo $c->getUsuario()->getNomePessoal();?>	
			</h6>
			<p class="nm_coment" id="com_ren_<?php echo $c->getId(); ?>">
				<?php echo $c->getComentario(); ?> 
			</p>
			<?php if($c->getUserId() == $_SESSION['id_user']){ 
				require "./Views/Templates/ComentarioTemplate/ren_ComentarioDivEdit.phtml";

				}?>
		</div>
	</div>
	<?php if($c->getUserId() == $_SESSION['id_user']){ 
		require "./Views/Templates/ComentarioTemplate/ren_ComentarioButtonEdit.phtml";
	}?>
</div>