<!DOCTYPE html>
<html>
<?php require_once "Templates/head.php"; ?>
<body>
<div class="container">
	
	<div class="row justify-content-center">
		<div class="col-8 ">
			<div class="col-4">
				<div id="errors" class="row"></div>
				<div class="row">
					<input type="text" id="nm_user" class="form-control-lg" placeholder="Nome usuario">
				</div>
			</div>
			<div class="col-6">
				<div class="row">
					<input type="text" id="nomePessoal" class="form-control-lg" placeholder="Nome Pessoal">
				</div>
			</div>
			<div class="col-5">
				<div class="row">
					<div class="row">
						<input type="password" id="senha" name="senha" class="form-control-lg" placeholder="Senha">
						<input type="password" id="confirm_senha" name="confirm_senha" class="form-control-lg" placeholder="Confirmar senha">
					</div>
				</div>
			</div>
			<br>
			<div class="row d-grid gap-2 col-6 mx-auto">
				<button id="confirm_cadastro" class="btn btn-outline-primary">
					<i class="bi bi-arrow-bar-right" ></i>Cadastre-se
				</button>
				<p>Já tem uma conta? <a href="?classe=Usuario&metodo=login">Logar</a></p>
			</div>
		</div>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script type="text/javascript">
	$("#confirm_cadastro").click(function(){
		$.ajax({
			type:'POST',
			url: '?classe=Usuario&metodo=manterUsuario',
			data:{
				nm_user: $("#nm_user").val(),
				nm_pessoal:$("#nomePessoal").val(),
				senha:$("#senha").val(),
				confirm_senha:$("#confirm_senha").val(),
			},
			success: function(result)
			{	
				if(result == "")
					window.location = '?classe=Usuario&metodo=login&sucess'
				document.getElementById('errors').innerHTML = result;
			}
		});

	});
</script>
</body>
</html>