<?php
	$v_posts = $this->getDados();
	$homura = $v_posts['postagens'];

?>
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<style type="text/css">
		body{
			background: #1c1e21;
		}
		textarea{
			resize: none;
		}
		img{
			background: grey;
			border-radius: 8px;
			border-color: black;
		}
		.row
		{
			color: grey;
			
		}
		.postagem
		{
			border-style: solid;
			border-width: 10px;
			border-radius: 8px;
			border-color: rgba(0, 0, 0, 0%);
			background: rgba(0, 0, 0, 0.4);
		}
	</style>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</head>

<body>
<?php require_once 'Templates/navbar.php'; ?>
<br>
<div id="success"></div>

<div class="container" id="main">
	<div class="col-8">

		<!-- Div para inserção de uma postagem -->
		<div class="row " id="user_insert_post">
			<div class="col-1">
				<img src="Views/img/usuarioPrincipal.png" width="50px" height="50px">
			</div>
			<div class="col-7">
				<!--A tag </textarea> não pode ter espaços entre a abertura e o fechamento
				senão na pagina ela terá espaços em branco -->
				<textarea  class="form-control" placeholder="Que se ta pensando amigo?" rows="2" name="postagem" id="postagem" style="font-size: 27px;"></textarea>
				<button id="postar" class="btn btn-primary">Postar</button>
			</div>
		</div>
		<br>
<!-- Renderização das Postagens junto com os Comentarios-->
<?php foreach ($homura as $postagem) { ?>

		<div class="row postagem">

			<!-- Div da foto,o nome de usuario, e talvez o botão de editar e deletar-->
			<?php require "Templates/PostagemTemplate/PostagemHeader.php"; ?>

			<!--Conteudo da Postagem -->
			<div class="row">
				<p id="txtPost<?php echo $postagem->getId(); ?>"><?php echo $postagem->getConteudo(); ?></p>	
			</div>

			<!-- Div do Botão de Curtida-->
			<?php require "Templates/PostagemTemplate/PostagemLikeDiv.phtml"; ?>

			<!--Area de Inserção do Comentario e exibição dos comentarios -->
			<?php require "Templates/PostagemTemplate/PostagemComentariosDiv.phtml"; ?>

<?php echo "<br><hr><br><br>";} ?>
		</div>	
	</div>
	
<!-- Modal de edição da postagem e outro contendo um Modal vazio que servirá para
	exibir todos os comentarios de uma postagem  ja que na principal só aparecerá 5 -->
<?php require_once "Templates/PostagemTemplate/PostagemModalEdit.php"; ?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="Views/js/PostagemJsFunctions.js"></script>
<script src="Views/js/ComentariosJsFunctions.js"></script>
<script src="Views/js/Ren_ComentariosJsFunctions.js"></script>

</body>
</html>