
<!DOCTYPE html>
<html>
<?php require_once "Templates/head.php"; ?>
<?php require_once "Templates/navbar.php"; ?>
<body>
<div class="container">
	<div class="row">
			<div class="col-3">
				<div class="row">
					<div class="card-group">
	  					<div class="card" style="position: static;">
	   					<?php
						echo '<img src="Views/img/fotosPerfil/'.$_SESSION["id_user"].'/'.$_SESSION['nm_foto'].'" class="figure-img card-img-top rounded" width="255px" height="255px">'
					?>
		    				<div class="card-body">
		    					<div id="errors"></div>
		    					<form method="POST" action="" enctype="multipart/form-data">
									<!--<input type="file" name="foto" >-->
								<div class="mb-3">
  									<label for="formFileSm" class="form-label">
  										Alterar Imagem
  									</label>
  									<input class="form-control form-control-sm" id="formFileSm" type="file" name="foto">
  									<button type="submit" class="btn btn-outline-primary">Confirmar</button>
								</div>
								</form>
		    				</div>

						</div>
					</div>
				</div>
			</div>
			<div class="col-3">
				<div class="row">
					<input type="text" id="nm_user disabledInput" class="form-control-lg" placeholder="Nome usuario" disabled value="<?php echo $_SESSION['nm_user']; ?>">
				</div>


				<div class="row">
				
					<input type="text" id="nomePessoal" class="form-control-lg" placeholder="Nome Pessoal" disabled value="<?php echo $_SESSION['nm_pessoal']; ?>"> 
				</div>


				<div class="row">
						<input type="password" id="senha" name="senha" class="form-control-lg" placeholder="Senha" disabled value="<?php echo $_SESSION['senha']; ?>">
				</div>
			</div>
			</div>
	
</div>
	

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script type="text/javascript">
/*	function enviarImg()
	{
		$.ajax({
			type:'POST',
			url: '?classe=Usuario&metodo=configu',
			data:{
				foto: $("#fotinha").val(),
			},
			success: function(result)
			{
				alert(result);
				location.reload();
			}
		})
	}*/
</script>
</body>
</html>