			<div class="row">
				<textarea class="comment" cols="5" rows="5" id="comment<?php echo $postagem->getId(); ?>" name="comment">
				</textarea>
			</div>
			<div class="row">
				<div class="col-1 right">
					<button class="btn btn-outline-primary comentar" value="<?php echo $postagem->getId(); ?>">Comentar</button>
				</div>
			</div>

			<!-- Atribuindo o vetor dos comentarios do post-->
			<?php $comentarios = $postagem->getCommentPost(); ?>

			<!-- Div dos Comentarios -->
			<div id="comentariosPost<?php echo $postagem->getId();  ?>">

				<?php for($i=0; $i<5; $i++) { 
					if(isset($comentarios[$i])){
				?>			
		 		<div class="row" >

					<div class="col-1">
						<img src="https://blogtectoy.com.br/wp-content/uploads/2020/02/sonic-the-hedgehog-2020-3.jpg" width="50px" height="50px">
					</div>

					<div class="col-10">
						<div class="">
							<h6 id="nomeuser">
									<?php echo $comentarios[$i]->getUsuario()->getNome();?>	
							</h6>
							<p> <?php echo $comentarios[$i]->getComentario(); ?> </p>
						</div>
					</div>
				</div>
					<?php }?>
				<?php } ?>

			</div>
</div>
		<div class="row">
			<button type="button" class="btn btn-primary mostrarComments" value="<?php echo $postagem->getId(); ?>"  data-toggle="modal" data-target="#exampleModal">
					Mostrar Mais
			</button>
		</div>